# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 62a6490f53d204f9d10b0466bee046b8ff3b5354a58a9ffa89fb678fb9735b028d241f0d364831c1d6536b60aa16becd9c3a1e0f086aa18b3fce1ae5bdd05224

test:
  secret_key_base: 04e24c1c8634b13b4fde7787db9aab2cc9541d42293a6e804962214ecd14329a376a98d4fb1e981550c1799116bff73ecae0a668464483214796950ba8224d5f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
